# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ./build
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/build') }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: bash ./build.sh


      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: # optional, default is artifact
            Create-Perfect-World-Server-Files
          path: 
            build/Create-Perfect-World-*-Server-Files.zip

      - name: Release file
        # You may pin to the exact commit or the version.
        # uses: djnicholson/release-action@e9a535b3eced09c460e07a84118fb74ae9b53236
        uses: djnicholson/release-action@v2.10
        with:
          # GitHub auth token
          token: ${{ secrets.GITHUB_TOKEN }}
          # Name of Release to add file to
          release-name: 0.4
          # Name of the tag for the release (will be associated with current branch)
          tag-name: 0.4
          # Name for the asset
          asset-name: Create-Perfect-World-Server.zip
          # File to release
          file: build/Create-Perfect-World-0.4-Server-Files.zip
